"""Add scheduled_time, desk layout, and menu expiry

Revision ID: 48e78509e667
Revises: 6b30a505842a
Create Date: 2026-02-04 08:38:50.901098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e78509e667'
down_revision = '6b30a505842a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('row', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('col', sa.Integer(), nullable=True))

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('desks', schema=None) as batch_op:
        batch_op.drop_column('col')
        batch_op.drop_column('row')
        batch_op.drop_column('block')

    # ### end Alembic commands ###
