"""Add time slots to desk booking

Revision ID: 829b1c66cbbf
Revises: 57d1c7d0f3b1
Create Date: 2026-02-03 11:28:17.058566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829b1c66cbbf'
down_revision = '57d1c7d0f3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk_bookings', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
